kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    openshift.io/display-name: notebook-without-ap-storage
  name: notebook-without-ap-storage
  namespace: rhods-notebooks
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: 'true'
    opendatahub.io/image-display-name: Jupyter | Minimal | CPU | Python 3.12
    notebooks.opendatahub.io/oauth-logout-url: 'https://rhods-dashboard-redhat-ods-applications.apps.sfpl33blocker-pool-tgjh9.aws.rh-ods.com/projects/rhods-notebooks?notebookLogout=notebook-without-ap'
    opendatahub.io/accelerator-name: ''
    openshift.io/description: ''
    openshift.io/display-name: notebook-without-ap
    opendatahub.io/legacy-hardware-profile-name: ''
    opendatahub.io/hardware-profile-namespace: ''
    notebooks.opendatahub.io/last-size-selection: Small
    opendatahub.io/username: htpasswd-cluster-admin-user
    opendatahub.io/hardware-profile-name: ''
    opendatahub.io/accelerator-profile-namespace: ''
    opendatahub.io/workbench-image-namespace: ''
  name: notebook-without-ap
  namespace: rhods-notebooks
  finalizers:
    - notebook-oauth-client-finalizer.opendatahub.io
  labels:
    app: notebook-without-ap
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
    opendatahub.io/user: htpasswd-2dcluster-2dadmin-2duser
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 8Gi
            requests:
              cpu: '1'
              memory: 8Gi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/rhods-notebooks/notebook-without-ap/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: non-standard-name
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/rhods-notebooks/notebook-without-ap/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                                  --ServerApp.token=''
                                  --ServerApp.password=''
                                  --ServerApp.base_url=/notebook/rhods-notebooks/notebook-without-ap
                                  --ServerApp.quit_button=False
                                  --ServerApp.tornado_settings={"user":"htpasswd-2dcluster-2dadmin-2duser","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.sfpl33blocker-pool-tgjh9.aws.rh-ods.com","hub_prefix":"/projects/rhods-notebooks"}
            - name: JUPYTER_IMAGE
              value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:2025.2'
            - name: GIT_SSL_CAINFO
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: PIP_CERT
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: REQUESTS_CA_BUNDLE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: SSL_CERT_FILE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: PIPELINES_SSL_SA_CERTS
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src/
              name: notebook-without-ap-storage
            - mountPath: /dev/shm
              name: shm
            - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
              name: trusted-ca
              readOnly: true
              subPath: ca-bundle.crt
            - mountPath: /opt/app-root/pipeline-runtimes/
              name: runtime-images
          image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:2025.2'
          workingDir: /opt/app-root/src
        - resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: oauth-proxy
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8443
              name: oauth-proxy
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/oauth/client
              name: oauth-client
            - mountPath: /etc/oauth/config
              name: oauth-config
            - mountPath: /etc/tls/private
              name: tls-certificates
          image: 'registry.redhat.io/openshift4/ose-oauth-proxy-rhel9@sha256:aa00b068c4c6a2428fd7832d8b53e2c8b0d2bb03799bb2a874ceb00be2bef33f'
          args:
            - '--provider=openshift'
            - '--https-address=:8443'
            - '--http-address='
            - '--openshift-service-account=notebook-without-ap'
            - '--cookie-secret-file=/etc/oauth/config/cookie_secret'
            - '--cookie-expire=24h0m0s'
            - '--tls-cert=/etc/tls/private/tls.crt'
            - '--tls-key=/etc/tls/private/tls.key'
            - '--upstream=http://localhost:8888'
            - '--upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
            - '--email-domain=*'
            - '--skip-provider-button'
            - '--client-id=notebook-without-ap-rhods-notebooks-oauth-client'
            - '--client-secret-file=/etc/oauth/client/secret'
            - '--scope=user:info user:check-access'
            - '--openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"notebook-without-ap","namespace":"$(NAMESPACE)"}'
            - '--logout-url=https://rhods-dashboard-redhat-ods-applications.apps.sfpl33blocker-pool-tgjh9.aws.rh-ods.com/projects/rhods-notebooks?notebookLogout=notebook-without-ap'
      enableServiceLinks: false
      serviceAccountName: notebook-without-ap
      volumes:
        - name: notebook-without-ap-storage
          persistentVolumeClaim:
            claimName: notebook-without-ap-storage
        - emptyDir:
            medium: Memory
          name: shm
        - configMap:
            items:
              - key: ca-bundle.crt
                path: ca-bundle.crt
            name: workbench-trusted-ca-bundle
            optional: true
          name: trusted-ca
        - configMap:
            name: pipeline-runtime-images
            optional: true
          name: runtime-images
        - name: oauth-config
          secret:
            defaultMode: 420
            secretName: notebook-without-ap-oauth-config
        - name: oauth-client
          secret:
            defaultMode: 420
            secretName: notebook-without-ap-oauth-client
        - name: tls-certificates
          secret:
            defaultMode: 420
            secretName: notebook-without-ap-tls
